function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 04-Sep-2018 20:56:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create xlabel
xlabel('Time(s)');

% Create title
title('Lab 1 Part 15');

% Create ylabel
ylabel('Encoder Ticks');

grid(axes1,'on');
% Create legend
legend(axes1,'show');

